version: '3.8'

services:
    rabbit:
        container_name: rabbit-carrier
        image:
            rabbitmq:3.13-management

        volumes:
            - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
            - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json:ro
        ports:
            - "5672:5672"
            - "15672:15672"